version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: blipee-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: blipee-redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    restart: unless-stopped

  pgbouncer:
    build: ./pgbouncer
    container_name: blipee-pgbouncer
    ports:
      - "6432:6432"
    environment:
      - DATABASES_HOST=${SUPABASE_DB_HOST}
      - DATABASES_PORT=5432
      - DATABASES_USER=${SUPABASE_DB_USER}
      - DATABASES_PASSWORD=${SUPABASE_DB_PASSWORD}
      - DATABASES_DATABASE=postgres
      - POOL_MODE=transaction
      - MAX_CLIENT_CONN=1000
      - DEFAULT_POOL_SIZE=25
    volumes:
      - ./pgbouncer/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "localhost", "-p", "6432"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis-data:
    driver: local