# Railway Nixpacks Configuration
# Multi-process deployment: Node.js Agent Worker + Python Prophet Service

[phases.setup]
nixPkgs = [
  "nodejs_20",
  "python311",
  "python311Packages.pip",
  "supervisor"
]

[phases.install]
cmds = [
  "npm ci --only=production --ignore-scripts",
  "pip install -r services/forecast-service/requirements.txt"
]

[phases.build]
# No build needed for worker
cmds = []

[start]
cmd = "supervisord -c supervisord.conf"
