# Railway Nixpacks Configuration
# This file tells Railway to skip the Next.js build and run the worker directly

[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci --only=production"]

[phases.build]
# Skip Next.js build entirely
cmds = ["echo 'Skipping Next.js build - deploying AI worker only'"]

[start]
cmd = "npx tsx services/ai-agent-orchestrator.ts"

[variables]
PORT = "8080"
