# Railway Configuration for Blipee AI Agent Worker
#
# This configuration deploys the agent worker as a separate long-running service
# The main Next.js app should be deployed separately to Vercel
#
# To deploy:
# 1. Install Railway CLI: npm install -g @railway/cli
# 2. Login: railway login
# 3. Link project: railway link
# 4. Deploy: railway up

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.worker"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Environment variables are set in Railway dashboard:
# - NEXT_PUBLIC_SUPABASE_URL
# - SUPABASE_SERVICE_ROLE_KEY
# - AGENT_POLL_INTERVAL_MS (default: 60000)
# - AGENT_HEARTBEAT_INTERVAL_MS (default: 30000)
