global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'blipee-monitor'

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Blipee OS Application Metrics
  - job_name: 'blipee-app'
    static_configs:
      - targets: ['host.docker.internal:3000']  # Next.js app
    metrics_path: '/api/monitoring/metrics'
    params:
      format: ['prometheus']
    scrape_interval: 30s
    scrape_timeout: 10s
    scheme: http

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # AlertManager
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']
    scrape_interval: 30s

  # Grafana
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    scrape_interval: 30s

  # Node Exporter (System metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # cAdvisor (Container metrics)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s

  # Redis Exporter (if you add one)
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis-exporter:9121']
  #   scrape_interval: 30s

  # Database metrics (if you add postgres_exporter)
  # - job_name: 'postgres'
  #   static_configs:
  #     - targets: ['postgres-exporter:9187']
  #   scrape_interval: 30s

  # Custom application endpoints
  - job_name: 'blipee-health'
    static_configs:
      - targets: ['host.docker.internal:3000']
    metrics_path: '/api/monitoring/health'
    scrape_interval: 60s
    scrape_timeout: 10s
    scheme: http

# Storage configuration
storage:
  tsdb:
    retention.time: 15d
    retention.size: 50GB

# Remote write configuration (for cloud providers)
# remote_write:
#   - url: "https://prometheus-remote-write.example.com/api/v1/write"
#     basic_auth:
#       username: "username"
#       password: "password"

# Remote read configuration
# remote_read:
#   - url: "https://prometheus-remote-read.example.com/api/v1/read"
#     basic_auth:
#       username: "username"
#       password: "password"